source :rubygems

gem 'rails', '3.2.2'
gem 'haml', '3.1.4'
gem 'configatron', '2.8.3'
gem 'airbrake', '~> 3.0.4'
gem 'factory_girl_rails', '1.2.0'
gem 'jquery-rails', '1.0.14'
gem 'therubyracer'
gem 'mysql2', '~> 0.3.11'

# Gems used only for assets and not required
# in production environments by default.
group "assets" do
  gem 'sass-rails', '~> 3.2.2'
  gem 'coffee-rails', '~> 3.2.2'
  gem 'uglifier', '>= 1.0.3'
end

group "development" do
  gem 'pry'
end

group "development", "test" do
  gem 'capybara', '~> 1.1.1'
  gem 'selenium-webdriver', '~> 2.5.0'
  gem 'rspec-rails', '~> 2.6.0'
  gem 'mocha', '~> 0.9.12'
  gem 'guard-rspec', '~> 0.5.0', :require => false
  gem 'growl', '~> 1.0.3', :require => false
  gem 'rb-fsevent', '~> 0.4.2', :require => false
  gem 'capistrano', '~> 2.11.2'
  gem 'capistrano-ext', '1.2.1', :require => nil
  gem 'capistrano_colors'
  gem 'fog', '~> 1.3.0'
end
