#!/usr/bin/env bash

# TODO: will need to be able to override some of the ~/.relevance_rails/aws_config.yml
# especially around the starter AMI

RAILS_APP="app_for_ci"

# exit if any statement fails
set -e

# TODO: run the unit tests BEFORE building a new gem

if [ `gem list relevance_rails --installed` = "true" ]; then
  echo "Removing old relevance_rails gem..."
  gem uninstall --verbose --all --executables relevance_rails 
  echo "Done"
fi

echo "Building new relevance_rails gem..."
rm -Rf relevance_rails-*.gem
gem build --verbose relevance_rails.gemspec 
echo "Done"

gem install --verbose --local relevance_rails-*.gem 

rm -Rf ./app_for_ci
relevance_rails new $RAILS_APP --database=postgresql

# TODO: this is NOT respecting the RVM gemset
cd $RAILS_APP

./script/rails generate deployment staging
git add .
git commit -m "Generated relevance_rails deployment scripts."

./script/rails generate fixtures
git add .
git commit -m "Generated relevance_rails fixtures."

