#!/bin/bash

RAILS_APP="app_for_ci"
EC2_MEMENTO_FILE="config/ec2_instance.txt"

function stop_server_and_exit {
  if [ -f $EC2_MEMENTO_FILE ]; then
    echo "Stopping newly-created server..."
    bundle exec rake provision:stopA
    echo "Done."
    exit 1
  fi  
}

#./script/ci 

source "$HOME/.rvm/scripts/rvm"
rvm gemset use $RAILS_APP
builtin cd $RAILS_APP

echo "Provisioning an EC2 instance..."
rm -f $EC2_MEMENTO_FILE
bundle exec rake provision:ec2 NAME="Nightly Build Testing" 
[ $? -ne 0 ] && stop_server_and_exit
echo "Done!"

echo "WIP: we haven't implemented farther than this yet!"
exit 1

TARGET_HOST=`bundle exec rake provision:current_ip`

echo "Generating relevance_rails deployment scripts..."
./script/rails generate deployment staging $TARGET_HOST
[ $? -ne 0 ] && stop_server_and_exit
git add .
git commit -m "Generated relevance_rails deployment scripts for $TARGET_HOST."
echo "Done."

echo "Capistrano: setup..."
cap staging deploy:setup
[ $? -ne 0 ] && stop_server_and_exit
echo "Done."

echo "Capistrano: deploying..."
cap staging deploy:cold
[ $? -ne 0 ] && stop_server_and_exit
echo "Done."

builtin cd -

echo "Running the acceptance tests against our newly-created server..."
HOST=$TARGET_HOST rake acceptance
[ $? -ne 0 ] && stop_server_and_exit
echo "Done."

echo "Terminating our newly-created server..."
bundle exec rake provision:destroy
echo "Done!"

